<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lastName</name>
   <tag></tag>
   <elementGuidId>282cbcd1-74f5-4fe4-bede-c1de5a642606</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;signatory_last_name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;signatory_last_name&quot;]</value>
      <webElementGuid>b10f5aeb-c317-499a-b976-147deb7e3de2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
